import { Metadata } from "next";
import React from "react";

export const metadata: Metadata = {
  title: "hyeyomi",
  description: "Generated by create next app",
};

export default function page() {
  return (
    <div>
      <h1 className="text-9xl">Profile page</h1>
    </div>
  );
}
